### PR TITLE
Add integration specs

### PR DESCRIPTION
**Pull request by diarisdiakite**
In this PR, we:
📃 Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
✔️ We don't use the bullet gem in this exercise - instead analyze the logs as showed in this [article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh)
✔️ **In this PR description we included the screenshots of your app's logs before(1) and after(2) the fix**
  
image

image

📃 We used Capybara to write integration tests for each view in your project.
- Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

📃 For the User index page:
✔️ I can see the username of all other users.
✔️ I can see the profile picture for each user.
✔️ I can see the number of posts each user has written.
✔️ When I click on a user, I am redirected to that user's show page.

📃 For the User show page:
✔️ I can see the user's profile picture.
✔️ I can see the user's username.
✔️ I can see the number of posts the user has written.
✔️ I can see the user's bio.
✔️ I can see the user's first 3 posts.
✔️ I can see a button that lets me view all of a user's posts.
✔️ When I click a user's post, it redirects me to that post's show page.
✔️ When I click to see all posts, it redirects me to the user's post's index page.

📃 For the User post index page:
✔️ I can see the user's profile picture.
✔️ I can see the user's username.
✔️ I can see the number of posts the user has written.
✔️ I can see a post's title.
✔️ I can see some of the post's body.
✔️ I can see the first comments on a post.
✔️ I can see how many comments a post has.
✔️ I can see how many likes a post has.
✔️ I can see a section for pagination if there are more posts than fit on the view.
✔️ When I click on a post, it redirects me to that post's show page.

📃 For the Post show page:
✔️ I can see the post's title.
✔️ I can see who wrote the post.
✔️ I can see how many comments it has.
✔️ I can see how many likes it has.
✔️ I can see the post body.
✔️ I can see the username of each commentor.
✔️ I can see the comment each commentor left.

**Made sure to include integration specs for any other features we implemented!**

### CODE REVIEW

**Review by Davidosky007 — APPROVED** [review]
Hi @diarisdiakite @flemton 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All tests passed 👍 
* Well-written PR 👍 
* No linter errors 👍 
* N+1 issue solved 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rloterh** [comment]
Hi @diarisdiakite 

Your project has been already approved. Can you kindly share why you submitted it again for approval?

Cheers!
Standing by..

**Comment by flemton** [comment]
> Hi @diarisdiakite
> 
> Your project has been already approved. Can you kindly share why you submitted it again for approval?
> 
> Cheers! Standing by..

Hi @rloterh, Sorry sir I was gonna submit a link to my repo of the same pair-programming project and mistakenly submitted this, my bad

**Review by rloterh — COMMENTED** [review]
Hi Newton, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your have submitted the wrong project under this project. Kindly ensure to submit the correct project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
